version: '2.3'

services:

  crawler:
    build:
      context: crawler/
    depends_on:
      - elasticsearch
    networks:
      - elk

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 15s
    networks:
      - elk

  #logstash:
  #  build:
  #    context: logstash/
  #  volumes:
  #    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #    - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #  ports:
  #    - "5000:5000"
  #  environment:
  #    LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #  networks:
  #    - elk
  #  depends_on:
  #    - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge

volumes:
  elasticdata:
